let strip = neopixel.create(DigitalPin.P0, 20, NeoPixelMode.RGB)
strip.setBrightness(255)
strip.showColor(neopixel.colors(NeoPixelColors.White))
let range1 = strip.range(0, 8)
let range2 = strip.range(9, 20)
let range3 = strip.range(0, 0)
range1.showColor(neopixel.colors(NeoPixelColors.Blue))
range2.showColor(neopixel.colors(NeoPixelColors.Green))
range3.showColor(neopixel.colors(NeoPixelColors.White))
strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Green))
strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Green))
strip.show()
basic.forever(function () {
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Orange))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(1000)
})
basic.forever(function () {
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Violet))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Orange))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(1000)
})
basic.forever(function () {
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(1000)
})
basic.forever(function () {
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Orange))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(1000)
})
basic.forever(function () {
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Orange))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Indigo))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Violet))
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(1000)
})
